# Generated by Django 5.2.5 on 2025-12-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insumo',
            options={'verbose_name_plural': 'Insumos'},
        ),
        migrations.AlterField(
            model_name='insumo',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
