# Generated by Django 5.2.5 on 2025-12-01 10:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_insumo_options_alter_insumo_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='plataforma',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('presencial', 'Presencial'), ('web', 'Página Web'), ('otro', 'Otro')], default='web', max_length=50),
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('email_cliente', models.EmailField(blank=True, max_length=254, null=True)),
                ('calificacion', models.IntegerField(help_text='Calificación del 1 al 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField()),
                ('aprobada', models.BooleanField(default=False, help_text='Marcar para mostrar en el sitio')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='mainApp.producto')),
            ],
            options={
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
